### ISSUE TITLE
Exception when MD013 line_length is specified in .markdownlintrc > 0.19.0

### ISSUE THREAD

**Issue by ericvw** [igorshubovych/markdownlint-cli#74] opened 2020-01-24 22:04 UTC
For the following Markdown file `test.md`:

```markdown
# Hello World
```

and `.markdownlintrc`:

```ini
[MD013]
line_length = 3
```

There is an exception thrown when executing `markdownlint test.md`:

```
/Volumes/development/scratch/markdownlint-cli-bug/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:648
      throw error;
      ^

Error: Property 'range' of onError parameter is incorrect.
    at throwError (/Volumes/development/scratch/markdownlint-cli-bug/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:376:13)
    at onError (/Volumes/development/scratch/markdownlint-cli-bug/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:404:9)
    at addError (/Volumes/development/scratch/markdownlint-cli-bug/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:343:3)
    at addErrorDetailIf (/Volumes/development/scratch/markdownlint-cli-bug/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:357:5)
    at /Volumes/development/scratch/markdownlint-cli-bug/markdownlint-cli/node_modules/markdownlint/lib/md013.js:82:9
    at forMetadata (/Volumes/development/scratch/markdownlint-cli-bug/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:191:5)
    at Array.forEach (<anonymous>)
    at forEachLine (/Volumes/development/scratch/markdownlint-cli-bug/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:189:16)
    at Object.MD013 [as function] (/Volumes/development/scratch/markdownlint-cli-bug/markdownlint-cli/node_modules/markdownlint/lib/md013.js:66:5)
    at forRule (/Volumes/development/scratch/markdownlint-cli-bug/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:466:20)
```

I am not familiar `node` nor `npm`, however, I was able to determine that the upgrade of `markdownlint@0.18.0` appears to be at play.  Downgrading to to `markdownlint@0.17.2` results in:

```
test.md:1 MD013/line-length Line length [Expected: 3; Actual: 13]
```

I did note that this does not appear to be an issue when converting the configuration to `.markdownlint.json`.  

I hope this helps and I wasn't sure whether to start an issue here or at https://github.com/DavidAnson/markdownlint.  Thanks!

**Comment by DavidAnson** [comment] 2020-01-24 22:35
This would be an error in the library itself. I’ll have a look soon. Thanks!

It should have nothing to do with how you specify the configuration - check that your JSON syntax is right?

**Comment by ericvw** [comment] 2020-01-24 22:45
I've converted the INI file to both the JSON and the YAML format and it does not exhibit the issue.

```shell-session
> cat config.yaml
MD013:
    line_length: 3

> markdownlint --config config.yaml test.md
test.md:1 MD013/line-length Line length [Expected: 3; Actual: 13]

> cat .markdownlintrc
[MD013]
line_length = 3

> markdownlint test.md
/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:648
      throw error;
      ^

Error: Property 'range' of onError parameter is incorrect.
    at throwError (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:376:13)
    at onError (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:404:9)
    at addError (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:343:3)
    at addErrorDetailIf (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:357:5)
    at /usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md013.js:82:9
    at forMetadata (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:191:5)
    at Array.forEach (<anonymous>)
    at forEachLine (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:189:16)
    at Object.MD013 [as function] (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md013.js:66:5)
    at forRule (/usr/local/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:466:20)
```

**Comment by DavidAnson** [comment] 2020-01-25 01:53
Okaaay.

New theory: The library code is perfect [ :) ] and the problem is that the RC configuration file parser is passing “3” as a string instead of as a number. See the last paragraph here: https://www.npmjs.com/package/rc#configuration-file-formats

I’m not sure what you could do to work around this, so the responsibility is still on me to fix it.

(If you are bored, try using the JSON format to pass “3” as a string explicitly and see if the same error pops out.)

**Comment by ericvw** [comment] 2020-01-25 20:55
Passing the string "3" does exhibit the same error.

What's interesting is why this hasn't manifested before.  Anyways, I converted to using YAML to work around the issue.

**Comment by DavidAnson** [comment] 2020-01-25 22:39
Cool, thank you for confirming! I expect to fix this tonight.

**Comment by DavidAnson** [comment] 2020-01-26 02:42
This should be fixed by https://github.com/DavidAnson/markdownlint/commit/3238ed4249f56a8d9e09f1ff33d307f1058fbee2 which will be included in the next release.

**Closed** 2020-02-04 03:46 UTC
Labels: bug
