### ISSUE TITLE
SyntaxError: Unexpected token } in JSON at position 525

### ISSUE THREAD

**Issue by iamnewton** [igorshubovych/markdownlint-cli#63] opened 2019-09-03 21:34 UTC
```
#10288: $ ./node_modules/.bin/markdownlint ./
undefined:28
}
^

SyntaxError: Unexpected token } in JSON at position 525
    at JSON.parse (<anonymous>)
    at exports.parse (/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/node_modules/rc/index.js:30:20)
    at Array.forEach (<anonymous>)
    at module.exports (/node_modules/rc/index.js:43:36)
    at readConfiguration (/node_modules/markdownlint-cli/markdownlint.js:28:16)
    at lintAndPrint (/node_modules/markdownlint-cli/markdownlint.js:220:18)
    at Object.<anonymous> (/node_modules/markdownlint-cli/markdownlint.js:237:3)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
```

**Comment by DavidAnson** [comment] 2019-09-03 22:25
It looks like this is coming from the RC package: https://www.npmjs.com/package/rc#standards

That package looks at a couple of different places for config information and my guess is that one of those has the broken JSON above. Could you please look around to see if that could be the case?

Unless you have a repository you can point us to, I’m not sure will be able to figure it out without knowing what the JSON looks like.

Thank you!

**Comment by iamnewton** [comment] 2019-09-03 22:57
it happens when I point it to a package that has my markdown config, e.g. `markdownlint --config ./node_modules/@scope/markdownlint-config/markdownlintrc.json --ignore node_modules --ignore .github --ignore CHANGELOG.md **/*.md`

here's the config

```json
{
  "MD001": true,
  "MD003": { "style": "atx" },
  "MD004": { "style": "dash" },
  "MD005": true,
  "MD006": true,
  "MD007": { "indent": 4 },
  "MD009": true,
  "MD010": true,
  "MD011": true,
  "MD012": true,
  "MD013": false,
  "MD014": true,
  "MD018": true,
  "MD019": true,
  "MD022": true,
  "MD023": true,
  "MD024": true,
  "MD025": true,
  "MD026": true,
  "MD027": true,
  "MD028": true,
  "MD029": { "style": "ordered" },
  "MD030": true,
  "MD031": true,
  "MD032": true,
  "MD033": true,
  "MD034": true,
  "MD035": { "style": "---" },
  "MD037": true,
  "MD038": true,
  "MD039": true,
  "MD040": true,
  "MD041": true,
  "MD042": true,
  "MD046": { "style": "fenced" },
  "MD047": true
}```

**Comment by DavidAnson** [comment] 2019-09-04 05:58
I've created a simple reproduction of your scenario. However, it behaves as expected (see below). Per above, I think `rc` may be finding one of its files in your scenario and that file is not valid JSON - please have a look.

```shell
david@Azure:~/markdownlint-cli-issue-63$ npm ls markdownlint-cli
/home/david/markdownlint-cli-issue-63
└── markdownlint-cli@0.18.0

david@Azure:~/markdownlint-cli-issue-63$ cat conf/markdownlintrc.json
{
  "MD001": true,
  "MD003": { "style": "atx" },
  "MD004": { "style": "dash" },
  "MD005": true,
  "MD006": true,
  "MD007": { "indent": 4 },
  "MD009": true,
  "MD010": true,
  "MD011": true,
  "MD012": true,
  "MD013": false,
  "MD014": true,
  "MD018": true,
  "MD019": true,
  "MD022": true,
  "MD023": true,
  "MD024": true,
  "MD025": true,
  "MD026": true,
  "MD027": true,
  "MD028": true,
  "MD029": { "style": "ordered" },
  "MD030": true,
  "MD031": true,
  "MD032": true,
  "MD033": true,
  "MD034": true,
  "MD035": { "style": "---" },
  "MD037": true,
  "MD038": true,
  "MD039": true,
  "MD040": true,
  "MD041": true,
  "MD042": true,
  "MD046": { "style": "fenced" },
  "MD047": true
}
david@Azure:~/markdownlint-cli-issue-63$ cat readme.md
# Heading

Text

    Code
david@Azure:~/markdownlint-cli-issue-63$ ./node_modules/.bin/markdownlint --config conf/markdownlintrc.json --ignore node_modules .
readme.md: 5: MD046/code-block-style Code block style [Expected: fenced; Actual: indented]
david@Azure:~/markdownlint-cli-issue-63$
```

**Comment by iamnewton** [comment] 2019-09-05 18:33
Are you suggesting that my configuration file is not valid JSON?

**Comment by DavidAnson** [comment] 2019-09-05 19:08
I think the `rc` package may be picking up one of the various files it supports and *that* file is not valid JSON. As you see above, the file you provided is valid and the basic scenario does not cause an error. There must be something else involved.

**Comment by DavidAnson** [comment] 2019-10-12 03:12
Closing due to the working example above and lack of a reproducible example.

**Closed by DavidAnson** 2019-10-12 03:12 UTC
Labels: question

**Comment by iamnewton** [comment] 2020-02-27 19:49
How can I debug where `rc` is picking things up?  No matter what I do, it seems to be picking up a file that it shouldn't and I can't figure out why

**Comment by DavidAnson** [comment] 2020-02-27 20:07
I don’t see that it has a verbose mode, so it might be helpful to instrument the code in node_modules temporarily. You could also fun a file watcher, but that’s likely to have a lot of noise.

**Comment by iamnewton** [comment] 2020-02-27 20:55
K.  And does the config file require that no file suffix be provided, e.g. `.json`?

**Comment by DavidAnson** [comment] 2020-02-27 21:00
Sorry, I don’t use `rc` myself, so I’d just go by the docs.

**Comment by DavidAnson** [comment] 2020-02-29 00:27
Yes, this project, markdownlint-cli uses rc for config in some cases. But I don’t use that aspect of it myself, so I don’t have much experience I can use to help here without debugging a reproduction.

**Comment by iamnewton** [comment] 2020-03-02 19:19
k.  i'll see what i can put together; thanks so much @DavidAnson for your time and patience with me on this, I truly appreciate it.
