### ISSUE TITLE
Property 'range' of onError parameter is incorrect when passing "**/target/**" as --ignore

### ISSUE THREAD

**Issue by juanchaur1** [igorshubovych/markdownlint-cli#62] opened 2019-08-07 16:42 UTC
When ignoring path that contains folder ```target``` there's an error:
However if I use something different that target it works just fine.

juanchaur$ npm run lint:md
```bash
> @ lint:md
> markdownlint ./ -r ./myRules -i **/library/** -i **/node_modules/** -i **/target/**
/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:575
      throw error;
      ^
Error: Property 'range' of onError parameter is incorrect.
    at throwError (/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:350:13)
    at onError (/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:378:9)
    at addError (/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:314:3)
    at addErrorContext (/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:349:5)
    at forEachInlineCodeSpan (/markdownlint-cli/node_modules/markdownlint/lib/md038.js:38:15)
    at forEachInlineCodeSpan (/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:275:13)
    at MD038.filterTokens (/markdownlint-cli/node_modules/markdownlint/lib/md038.js:19:9)
    at forToken (/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:143:7)
    at Array.forEach (<anonymous>)
    at filterTokens (/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:141:17)
```

I'm running it in a project structure like this:
```
- projectA
	- README.md
	- node_modules
- subdir
	- projectB
		- node_modules
		- docs.md
		- target
	- projectC
		- node_modules
		- docs
			- a.md
			- b.md
        - target
- project X
	- vendor
	- site
		- page1.md
		- page2.md
```

**Comment by DavidAnson** [comment] 2019-08-07 16:48
Rule MD038 seems to be crashing on one of the input files. Can you figure out which one or point me at the repository and I will track it down?

**Comment by juanchaur1** [comment] 2019-08-07 19:08
So for instance my java submodule has a target with a README.md
Like this:
```submodule/cdn/target/test-classes/library/ansible-fastly/README.md: 128: MD013/line-length Line length [Expected: 99; Actual: 103]```

**Comment by DavidAnson** [comment] 2019-08-07 19:23
That file shouldn’t be getting looked at if the ignores are working as you intend.  I am on a phone and can not experiment, but could you please try changing to  “-i **/target/*” to see if that helps? If not, I can try duplicating your folder structure - but a pointer to the repository would be ideal if possible.

**Comment by juanchaur1** [comment] 2019-08-07 19:45
It fails with the same error.
The repositories are private so I can't do that.
But it's a java project with multiple submodules and I'm running package.json script from root
```bash
juanchaur$ npm run lint:md

> @ lint:md /Users/juanchaur/Project
> markdownlint ./ -r node_modules/my-coding-standards/md-lint/custom_linters/ -i **/target/*

**Comment by DavidAnson** [comment] 2019-08-07 20:45
I’ll create a repository in the next few days to attempt to reproduce some of what you’re seeing. In the meanwhile, can you please share the version number of markdownlint-cli you are using?

**Comment by juanchaur1** [comment] 2019-08-07 21:07
The version is:
```json
{
   "markdownlint-cli": "^0.17.0"
}

**Comment by DavidAnson** [comment] 2019-08-10 05:40
I've created a repository that tries to mirror the structure of yours. As you can see below, things seem to be working as expected. Please sync/clone https://github.com/DavidAnson/markdownlint-cli-issue-62 and try for yourself. If it works for you as well, please make whatever changes you need to reproduce the problem you're seeing and describe them or send a PR - then I'll investigate. Thanks!

```
C:\T>git clone https://github.com/DavidAnson/markdownlint-cli-issue-62
Cloning into 'markdownlint-cli-issue-62'...

C:\T>cd markdownlint-cli-issue-62

C:\T\markdownlint-cli-issue-62>tree /f /a
C:.
|   .gitignore
|   good.md
|   package.json
|   README.md
|
+---directory
|   +---project
|   |   |   good.md
|   |   |
|   |   \---node_modules
|   |           bad.md
|   |           good.md
|   |
|   \---target
|           bad.md
|           good.md
|
\---project
    |   good.md
    |
    \---node_modules
            bad.md
            good.md

C:\T\markdownlint-cli-issue-62>npm i
added 33 packages from 26 contributors and audited 43 packages in 2.191s

C:\T\markdownlint-cli-issue-62>npm run mdl-all

> markdownlint-cli-issue-62@ mdl-all C:\T\markdownlint-cli-issue-62
> markdownlint ./

directory/project/node_modules/bad.md: 1: MD047/single-trailing-newline Files should end with a single newline character
directory/target/bad.md: 1: MD047/single-trailing-newline Files should end with a single newline character
node_modules/argparse/CHANGELOG.md: 1: MD041/first-line-heading/first-line-h1 First line in file should be a top level heading [Context: "1.0.10 / 2018-02-15"]
...
node_modules/uc.micro/README.md: 6: MD013/line-length Line length [Expected: 80; Actual: 96]
project/node_modules/bad.md: 1: MD047/single-trailing-newline Files should end with a single newline character

C:\T\markdownlint-cli-issue-62>npm run mdl-inm

> markdownlint-cli-issue-62@ mdl-inm C:\T\markdownlint-cli-issue-62
> markdownlint ./ --ignore **/node_modules/**

directory/target/bad.md: 1: MD047/single-trailing-newline Files should end with a single newline character

C:\T\markdownlint-cli-issue-62>npm run mdl-inmt

> markdownlint-cli-issue-62@ mdl-inmt C:\T\markdownlint-cli-issue-62
> markdownlint ./ -i **/node_modules/** -i **/target/**

C:\T\markdownlint-cli-issue-62>
```

**Comment by DavidAnson** [comment] 2019-10-12 03:10
Closing based on the working example provided above.

**Closed by DavidAnson** 2019-10-12 03:10 UTC
Labels: question
