### ISSUE TITLE
0.23.0 Completely broken?

### ISSUE THREAD

**Issue by waylan** [igorshubovych/markdownlint-cli#93] opened 2020-05-06 13:42 UTC
It would seem that the most recent release (0.23.0 has complete broken. From my [CI logs][1]:

```
markdown-lint run-test: commands[0] | markdownlint README.md CONTRIBUTING.md docs/
526/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:799
527      throw error;
528      ^
529
530TypeError: content.trimEnd is not a function
531    at handleRunEnd (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md037.js:38:27)
532    at MD037.forEachLine (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md037.js:133:13)
533    at forMetadata (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:256:5)
534    at Array.forEach (<anonymous>)
535    at forEachLine (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/markdownlint-cli/node_modules/markdownlint/helpers/helpers.js:254:16)
536    at Object.MD037 [as function] (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/md037.js:71:5)
537    at forRule (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:593:20)
538    at Array.forEach (<anonymous>)
539    at lintContent (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:639:14)
540    at lintContentWrapper (/home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/markdownlint-cli/node_modules/markdownlint/lib/markdownlint.js:679:12)
541ERROR: InvocationError for command /home/travis/.nvm/versions/node/v8.9.1/bin/markdownlint README.md CONTRIBUTING.md docs/ (exited with code 1)
```

The error doesn't tell me which file it failed on, so it's difficult to narrow down. Although, `md037.js` seems to be involved, so perhaps it is related to that rule. Unfortunately, I haven't been able to update my local install (`npm update -g markdownlin-cli` does nothing) so I haven't been able to try things locally to narrow the issue down.

I'm guessing the issue is directly related to 0.23.0 at the error first appeared yesterday after that version was released. However, I can't actually be certain as the version in use is not reported to me in the CI logs.

[1]: https://travis-ci.org/github/mkdocs/mkdocs/jobs/683538509

**Comment by DavidAnson** [comment] 2020-05-06 16:16
This looks like a duplicate of the following issue: https://github.com/igorshubovych/markdownlint-cli/issues/90#issuecomment-624266496

Node.js 8 stopped being supported by Node at the end of last year. Version 0.22.0 of this project stopped supporting it on February 8.

**Comment by waylan** [comment] 2020-05-06 22:09
Ah, okay. Sorry, but I'm not that familiar with how Node works. In Python, we set which versions of Python our package is compatible with and the installer won't even attempt to install an incompatible version. Seems crazy to me that node doesn't have something like that.

Now I have to figure out how to get our CI server to either use a new version of node or an older version of markdownlint-cli.

**Closed** 2020-05-06 23:17 UTC

**Comment by DavidAnson** [comment] 2020-05-07 04:34
Glad you got this sorted!

**Comment by orsinium** [comment] 2020-05-15 13:20
Same here. I used `language: generic` on Travis CI, and it worked. There is working Travis CI config:

```
matrix:
  include:
    - name: markdown lint
      language: node_js
      node_js: "14"
      install:
        - npm install -g markdownlint-cli
      script:
        - bash -c "markdownlint --config markdownlint.json **/*.md"
```

I hope it helps someone.

**Comment by DavidAnson** [comment] 2020-05-15 16:58
Note that your script above is implicitly installing the latest version of the CLI which means you will get breaking changes as soon as they are published and that could fail your CI. You may want to explicitly specify a version so that happens under your control instead. Here’s an example: https://github.com/mkdocs/mkdocs/commit/5ff7e02e4bc4f1fae1d07b49c61b67b5a4e9f596
